# parts of this extended COL checklist configuration was copied from the backbone configs:
# YAML syntax problems can be verified with https://www.yamllint.com
# https://github.com/gbif/gbif-configuration/blob/master/cli/nub/config/clb-nub.yaml

# dataset metadata with project variables to be applied to each release
alias: "COL-{date,yyyy-MM-dd}"
title: Catalogue of Life 
version: "XR {date,yyyy-MM-dd}"
description: |
  The Catalogue of Life Checklist is a programmatically extended version of the COL Base Checklist from {date,yy.M}.
  It merges in additional names and other information from several often non global resources 
  with the aim to increase the coverage of names, include very recently published names and fill gaps in the COL Base checklist.
  For this taxonomic treatments present in Plazis Treatmentbank and various Pensoft journals that publish to ChecklistBank are included.

# taxon to use for incertae sedis names during merges
incertaeSedis:
  name: incertae sedis
  rank: unranked
  status: PROVISIONALLY_ACCEPTED
  classification: 
    - 
      name: Biota
      rank: unranked

removeEmptyGenera: false

# activate the homotypic grouping?
homotypicConsolidation: true
homotypicConsolidationThreads: 8

#More about decisions https://github.com/CatalogueOfLife/data/issues/816

decisions:
  "2317":
    - mode: reviewed
      subject:
        name: Cercopoidea
        rank: superfamily
    - mode: reviewed
      subject:
        name: Fulgoromorpha
        rank: infraorder

issueExclusion:
- UNPARSABLE_NAME
- UNPARSABLE_AUTHORSHIP
- NULL_EPITHET
- INDETERMINED
- HIGHER_RANK_BINOMIAL
- MISSING_GENUS
- INCONSISTENT_NAME

blockedNames:
  - Diptera larva
  - Flowering plant
  - Gen # https://github.com/gbif/checklistbank/issues/230
  - Gen sp
  - Gen spec
  - Grey lichens
  - Incertae  # https://github.com/gbif/portal-feedback/issues/1845
  - Lichens
  - Lower plants (Lichens)
  - Scientific # https://github.com/gbif/portal-feedback/issues/2726
  - Scientific name
  - Status unresolved
  - Strawberry witches phytoplasma
  - Unaccepted  
  - Unknown
  - Hirundo D'Orbigny & Lafresnaye, 1838 # https://github.com/gbif/portal-feedback/issues/3250
  - Sedum rupestre Hacq. ex Nyman, 1879 # https://github.com/gbif/checklistbank/issues/233
  - Tricholaema leucomelan namaqua  # https://github.com/gbif/checklistbank/issues/46
  - Katharellidae  #https://github.com/CatalogueOfLife/xcol/issues/130
  - Animalia # https://github.com/CatalogueOfLife/xcol/issues/164
  - Plantae
 

# List of regular expression patterns for scientific names that are globally blocked from any source.
# Patterns are case insensitive and must not be anchored at the front. Any match will block the name.
# Because of how YAML treats backslashes in double-quoted strings, note that all backslashes in a regex expression must be escaped when using double quotes. 
# For example, all of these are valid:
#   expression: \w*
#   expression: '\w*'
#   expression: "\\w*"
# Best to avoid using double quotes!
#
# You can test regex patterns here nicely: https://regex101.com
#
blockedNamePatterns:
 - '^\? [a-z]+'
 # unwanted pattenrs from NCBI
 - '(?i)\b(environmental sample|unidentified|uncultured)\b'
 # unwanted group names from zoobank
 - '.*\grp\..*'
 # unwanted patterns from iBOLD https://github.com/gbif/backbone-feedback/issues/28#issuecomment-2220382593
 - '\b(spnr|nr|nsp|morphospecies|Gen novum)\b/i'
 - '\b(indet|indeterminate)\b/i' # to be removed after 21 September as its part of the name parser then
 # unwanted hybrid placeholders from GRIN
 - '\bhybr\b'
 # patterns from Plazi
 - '\b(Gen_Indet|Gen indet)\b/i'


# epithets keyed by family
basionymExclusions:
  Chrysomelidae:
    - nigripennis # https://github.com/gbif/checklistbank/issues/179
  Orchidaceae:
    - extinctoria # https://github.com/gbif/portal-feedback/issues/4170
  Cicadellidae:
    - guttulata # https://github.com/CatalogueOfLife/testing/issues/135
  Nymphalidae:
    - mylitta # https://github.com/gbif/portal-feedback/issues/4332


# List of uninomials (genus & above) known to be unique across all life for a given rank
# Only the first appearance of the name will create a taxon
# all subsequent ones will be merged into the first
enforceUnique:
  GENUS:
    - Anas


# specific list of CLB dataset keys to exclude as sectors being created for aboves source publisher keys
sourceDatasetExclusion:
- 292056 # genus chromista https://github.com/plazi/community/issues/349
- 4130 # Creates matching error https://github.com/CatalogueOfLife/data/issues/792
- 6675 # excluded to avoid duplicates
- 30084 # excluded due to wrong higher classification in all names  https://github.com/CatalogueOfLife/xcol/issues/179
- 28224 # temporaly blocked, https://github.com/plazi/community/issues/337
# exclusion due to classification mismatch can be included when plazi fixes the issues

