# dataset metadata with project variables to be applied to each release
alias: "XCOL{date,yy.M}"
title: Catalogue of Life Extended Checklist 
version: "{date,yyyy-MM-dd}"
description: |
  The Catalogue of Life Extended Checklist is an programmatically extended version of the regular COL Checklist COL{date,yy.M}.
  It merges in additional names and other information from several often non global resources 
  with the aim to increase the coverage of names, include very recently published names and fill gaps in the regular COL checklist.
  For this taxonomic treatments present in Plazis Treatmentbank and various Pensoft journals that publish to ChecklistBank are included.

# GBIF publisher keys to follow and create sectors for if missing
sourcePublisher: 
#  - bb922300-7ddb-11de-a300-90ac77aa923f # Plazi
  - bb922300-7ddb-11de-a300-90ac77aa923f # ZooKeys
#  - 750a8724-fa66-4c27-b645-bd58ac5ee010 # Biodiversity Data Journal

# specific list of CLB dataset keys to exclude as sectors being created for aboves source publisher keys
sourceDatasetExclusion: 
  - 2048 # Catalogue of Tenebrionidae (Coleoptera) of North America

# activate the homotypic grouping?
groupBasionyms: true


# epithets keyed by family
basionymExclusions:
  Chrysomelidae:
    - nigripennis # https://github.com/gbif/checklistbank/issues/179
  Orchidaceae:
    - extinctoria # https://github.com/gbif/portal-feedback/issues/4170
  Cicadellidae:
    - guttulata # https://github.com/CatalogueOfLife/testing/issues/135
  Nymphalidae:
    - mylitta # https://github.com/gbif/portal-feedback/issues/4332


# Wrong homonyms above species rank that should be excluded from the extended release, 
# regardless of which source they came from.
# List of canonical names with its direct parent to identifiy the version to be removed.
# All other names with the same canonical name, but different parent, are kept.
homonymExclusions:  

  # order
  Diplomonadida:
    - Eopharyngea
  Piroplasmida:
    - Miozoa
  Trichomonadida:
    - Trichomonadea
  
  # families
  Glossoscolecidae:
    - Crassiclitellata
  
  # genera
  Abisara:
    - Riodinidae
  Actinosphaera:
    - Watznaueriaceae
  Aethia:
    - Lonchocephalidae
  Alesa:
    - Riodinidae
  Anama:
    - Cerambycidae
  Ancyluris:
    - Riodinidae
  Aniculus:
    - Paguridea
  Anteros:
    - Riodinidae
  Apodemia:
    - Riodinidae
  Argyrogrammana:
    - Riodinidae
  Aricoris:
    - Riodinidae
  Arpadites:
    - Trachyceratidae
  Audre:
    - Riodinidae
  Axiagasta:
    - Geometridae
  Babesia:
    - Aegyptianella
  Baeotis:
    - Riodinidae
  Barbicornis:
    - Riodinidae
  Barroisiceras:
    - Muniericeratidae
  Bartramia:
    - Bryopsida
  Cadosinopsis:
    - Thoracosphaeraceae
  Calephelis:
    - Riodinidae
  Calydna:
    - Riodinidae
  Caria:
    - Riodinidae
  Carterus:
    - Curculionidae
  Cerceris:
    - Masaridae
  Chaetophora:
    - Chaetophoraceae
  Chalodeta:
    - Riodinidae
  Chamaelimnas:
    - Riodinidae
  Charis:
    - Riodinidae
  Chorinea:
    - Riodinidae
  Cicada:
    - Animalia
    - Cicadellidae
  Clionites:
    - Sandlingitidae
  Cnemidophorus:
    - Curculionidae
  Coccinella:
    - Hydrophilidae
    - Mollusca
  Colaciticus:
    - Riodinidae
  Cremna:
    - Riodinidae
  Curculionites:
    - Coleoptera
  Cyrtia:
    - Syringothyrididae
  Dardanus:
    - Paguridae
  Dicallaneura:
    - Riodinidae
  Discias:
    - Bresiliidae
  Dodona:
    - Riodinidae
  Ducellieria:
    - Ducellieriaceae
  Dysmathia:
    - Riodinidae
  Ematurgina:
    - Riodinidae
  Emesis:
    - Riodinidae
  Endemosarca:
    - Endemosarcaceae
  Esthemopsis:
    - Riodinidae
  Eurybia:
    - Riodinidae
  Euselasia:
    - Riodinidae
  Heliodiscus:
    - Bacillariophyceae
  Hermathena:
    - Riodinidae
  Heteronyx:
    - Curculionidae
  Hiatella:
    - Lyonsiidae
  Hirundo:
    - Annelida
  Hyphilaria:
    - Riodinidae
  Ichneumon:
    - Eulophidae
  Imelda:
    - Riodinidae
  Ithomeis:
    - Riodinidae
  Ithomiola:
    - Riodinidae
  Ixodes:
    - Aves
  Jerdonia:
    - Aves # https://github.com/gbif/portal-feedback/issues/2724
  Komiella:
    - Rugosochonetidae
  Lasaia:
    - Riodinidae
  Lemonias:
    - Riodinidae
  Lepricornis:
    - Riodinidae
  Leucochimona:
    - Riodinidae
  Ligniera:
    - Plasmodiophoraceae
  Lyropteryx:
    - Riodinidae
  Lytoceras:
    - Tetragonitidae
  Melanis:
    - Riodinidae
  Membranosorus:
    - Plasmodiophoraceae
  Menander:
    - Riodinidae
  Mesene:
    - Riodinidae
  Mesenopsis:
    - Riodinidae
  Mesosemia:
    - Riodinidae
  Metacharis:
    - Riodinidae
  Milvus:
    - Falconidae
  Monethe:
    - Riodinidae
  Musca:
    - Tachinidae
  Napaea:
    - Riodinidae
  Necyria:
    - Riodinidae
  Nymphidium:
    - Riodinidae
  Octomyxa:
    - Plasmodiophoraceae
  Octotoma:
    - Dryophthoridae
  Oligomerus:
    - Ptinidae
  Omma:
    - Cupedidae
  Pachythone:
    - Riodinidae
  Panara:
    - Riodinidae
  Pandemos:
    - Riodinidae
  Paracrangon:
    - Hippolytidae
  Parahoplites:
    - Deshayesitidae
  Paralaxita:
    - Riodinidae
  Pelecanus:
    - Dinosauria
  Phaenochitonia:
    - Riodinidae
  Planaria:
    - Nemertea
  Plasmodiophora:
    - Plasmodiophoraceae
  Platyrhynchus:
    - Attelabidae
  Pleuridium:
    - Archidiaceae
  Polycaena:
    - Riodinidae
  Polymyxa:
    - Plasmodiophoraceae
  Praetaxila:
    - Riodinidae
  Productus:
    - Aulostegidae
  Productus:
    - Linoproductidae
  Productus:
    - Productellidae
  Psorergates:
    - Cheyletidae
  Pterographium:
    - Riodinidae
  Raphidiophrys:
    - Raphidiophryidae
  Rodinia:
    - Riodinidae
  Roeberella:
    - Riodinidae
  Semomesia:
    - Riodinidae
  Setabis:
    - Riodinidae
  Siseme:
    - Riodinidae
  Sorodiscus:
    - Plasmodiophoraceae
  Sphex:
    - Pompilidae
  Sphex:
    - Vespidae
  Spirifer:
    - Paeckelmanellidae
  Spiriferina:
    - Paraspiriferinidae
  Spiriferina:
    - Spiriferellidae
  Sporomyxa:
    - Plasmodiophoraceae
  Stichelia:
    - Riodinidae
  Symmachia:
    - Riodinidae
  Syrmatia:
    - Riodinidae
  Taxila:
    - Riodinidae
  Teratophthalma:
    - Riodinidae
  Tetramyxa:
    - Plasmodiophoraceae
  Tettigonia:
    - Cicadidae
  Thalassomyces:
    - Ellobiopsidae
  Themone:
    - Riodinidae
  Theope:
    - Riodinidae
  Vrilletta:
    - Curculionidae
  Woronina:
    - Plasmodiophoraceae
  Xenandra:
    - Riodinidae
  Zelotaea:
    - Riodinidae

