#!/bin/bash

my_dir=$(pwd)
acef_dir="$(dirname "$my_dir")" 

rm -rf /tmp/acef
mkdir /tmp/acef
if [ ${?} != 0 ]
then
	echo "Could not create temp directory /tmp/acef"
	exit 1
fi

database_id="${1}"

if [ "x${database_id}" = "x" ]
then
	echo "$(date '+%Y-%m-%d %H:%M:%S') Retrieving GSD IDs"
	mysql --defaults-extra-file=my.cnf -e 'SELECT record_id FROM `databases`' > /tmp/acef/database_ids.txt
	echo "$(date '+%Y-%m-%d %H:%M:%S') Executing one-off SQL"
	mysql --defaults-extra-file=my.cnf < once.sql
	echo "$(date '+%Y-%m-%d %H:%M:%S') Clearing directory ${acef_dir}"
	rm -rf "${acef_dir}/*.gz"
	rm -rf "${acef_dir}/higher-classification.dwca.zip"
else
	echo $database_id > /tmp/acef/database_ids.txt
fi

dsql=${my_dir}/datasets_generated.sql
echo "" > ${dsql}
while read -r line
do
	if [ "${line}" = "record_id" ]
	then
		# Skip header
		continue
	fi
    echo "$(date '+%Y-%m-%d %H:%M:%S') Processing database: ${line}"
	mkdir /tmp/acef/${line}
	chmod -R 777 /tmp/acef/${line}
    sed "s/__OUTPUT_DIR__/\/tmp\/acef\/${line}/g" assembly_db_to_acef.sql > /tmp/acef/temp.sql
    sed -i "s/__DATABASE_ID__/${line}/g" /tmp/acef/temp.sql 
    mysql --defaults-extra-file=my.cnf < /tmp/acef/temp.sql
    cd "/tmp/acef/${line}"
    zip_file="/tmp/acef/${line}.tar.gz"
    tar czf ${zip_file} *.txt
    mv ${zip_file} ${acef_dir}
    cd ${my_dir}
    echo "INSERT INTO dataset (key, code, title) VALUES (1000+${line}, null, 'GSD');" >> ${dsql}
done < /tmp/acef/database_ids.txt
cat datasets-append.sql >> ${dsql}

# For higher classification we create a separate DWCA file, but we still
# put it next to the other files generated by this script (so under the
# ACEF directory)
if [ "x${database_id}" = "x" ]
then
	echo "$(date '+%Y-%m-%d %H:%M:%S')  Creating DwCA for higher classification"
	mkdir /tmp/acef/higher-classification
	cp higher-classification.meta.xml  /tmp/acef/higher-classification/meta.xml
	mysql --defaults-extra-file=my.cnf < higher-classification.sql > /tmp/acef/higher-classification/taxa.txt
	cd /tmp/acef/higher-classification
	zip higher-classification.dwca.zip *
	mv higher-classification.dwca.zip ${acef_dir}
	cd ${my_dir}
fi

