# parts of this extended COL checklist configuration was copied from the backbone configs:
# YAML syntax problems can be verified with https://www.yamllint.com
# https://github.com/gbif/gbif-configuration/blob/master/cli/nub/config/clb-nub.yaml

# dataset metadata with project variables to be applied to each release
metadata:
  alias: "COL{date,yy.M} XR"
  title: Catalogue of Life
  version: "{date,yyyy-MM-dd} XR"
  description: |
    This eXtended Release (XR) of the Catalogue of Life is a programmatically enhanced version of the Catalogue of Life base release {base.version} ({base.alias}).
    It integrates information from {mergeSources} overlapping taxonomic and nomenclatural global, regional, national and management data sources (checklists) 
    as well as originating from digitised literature available in Catalogue of Life's infrastructure ChecklistBank.
    
    The XR addresses several gaps of the Catalogue of Life base release and also enriches the existing names with information such as authorships, references, and vernacular names. 
    It also adds molecular data, such as barcode index numbers or operational taxonomic units to the Catalogue of Life. 
    Higher taxonomy is being added only in selected groups with important gaps. 
    Meanwhile, the information from the global data sources of the Catalogue of Life base release remains unmodified.

    This enhanced process is continuously evolving and undergoing quality control checks by COL editors and its community. 
    Due to its programmatic nature as well as the taxonomic and nomenclatural differences among the data sources used, some issues may arise. 
    We therefore caution the user that taxonomic sectors in the Catalogue of Life eXtended Release are not as scrutinized by taxonomists as is the case with the Catalogue of Life the base release.

    If you find any problem please log it in the [COL’s data GitHub repository](https://github.com/CatalogueOfLife/data/issues/new?template=xcol-content-feedback.md).
    We will do our best to resolve these issues as soon as possible.

  completeness: 90
  #conversion:
  #  url: https://github.com/CatalogueOfLife/backend/blob/master/core/src/main/java/life/catalogue/release/XRelease.java
  #  description: Describe how the merging works

  # If true a release will include as its authors all authors of all it's sources.
  addSourceAuthors: true

  # If true a release will include as its authors all contributors of the project (not source contributors).
  addContributors: true

  # Optional list of dataset types to exclude from sources to generate the release authors from. E.g. ARTICLE to exclude all authors from Plazi and BDJ sources.
  authorSourceExclusion: 
    - ARTICLE


# taxon to use for incertae sedis names during merges
incertaeSedis:
  name: incertae sedis
  rank: unranked
  status: PROVISIONALLY_ACCEPTED
  classification: 
    - 
      name: Biota
      rank: unranked

failOnSyncErrors: false
removeEmptyGenera: false

# activate the homotypic grouping?
homotypicConsolidation: true
homotypicConsolidationThreads: 8

# More about decisions 
# https://github.com/CatalogueOfLife/data/issues/816

# A decision subject can have any of these properties, but must at least always have a name:
#   name: Abies alba
#   authorship: Mill.
#   rank: species
#   status: accepted
#   parent: Abies
decisions:
  2317: # 3i Auchenorrhyncha
    - mode: reviewed
      subject:
        name: Cercopoidea
        rank: superfamily
    - mode: reviewed
      subject:
        name: Fulgoromorpha
        rank: infraorder

issueExclusion:
- UNPARSABLE_NAME
- UNPARSABLE_AUTHORSHIP
- NULL_EPITHET
- INDETERMINED
- HIGHER_RANK_BINOMIAL
- MISSING_GENUS
- INCONSISTENT_NAME

blockedNames:
  - Diptera larva
  - Flowering plant
  - Gen # https://github.com/gbif/checklistbank/issues/230
  - Gen sp
  - Gen spec
  - Grey lichens
  - Incertae  # https://github.com/gbif/portal-feedback/issues/1845
  - Lichens
  - Lower plants (Lichens)
  - Scientific # https://github.com/gbif/portal-feedback/issues/2726
  - Scientific name
  - Status unresolved
  - Strawberry witches phytoplasma
  - Unaccepted  
  - Unknown
  - Hirundo D'Orbigny & Lafresnaye, 1838 # https://github.com/gbif/portal-feedback/issues/3250
  - Sedum rupestre Hacq. ex Nyman, 1879 # https://github.com/gbif/checklistbank/issues/233
  - Tricholaema leucomelan namaqua  # https://github.com/gbif/checklistbank/issues/46
  - Katharellidae  #https://github.com/CatalogueOfLife/xcol/issues/130
  - Animalia # https://github.com/CatalogueOfLife/xcol/issues/164
  - Plantae
 

# List of regular expression patterns for scientific names that are globally blocked from any source.
# Patterns are case insensitive and must not be anchored at the front. Any match will block the name.
# Because of how YAML treats backslashes in double-quoted strings, note that all backslashes in a regex expression must be escaped when using double quotes. 
# For example, all of these are valid:
#   expression: \w*
#   expression: '\w*'
#   expression: "\\w*"
# Best to avoid using double quotes!
#
# You can test regex patterns here nicely: https://regex101.com
#
blockedNamePatterns:
 - '^\? [a-z]+'
 # unwanted pattenrs from NCBI
 - '(?i)\b(environmental sample|unidentified|uncultured)\b'
 # unwanted group names from zoobank
 - '\bgrp\.\b'
 - '\btobedeleted'
 # unwanted patterns from iBOLD https://github.com/gbif/backbone-feedback/issues/28#issuecomment-2220382593
 - '\b(spnr|nr|nsp|morphospecies|Gen novum)\b/i'
 - '\b(indet|indeterminate)\b/i' # to be removed after 21 September as its part of the name parser then
 # unwanted hybrid placeholders from GRIN
 - '\bhybr\b'
 # patterns from Plazi
 - '\b(Gen_Indet|Gen indet)\b/i'
 # https://github.com/plazi/community/issues/387
 - '\bundefined\b'


# epithets keyed by family
basionymExclusions:
  Chrysomelidae:
    - nigripennis # https://github.com/gbif/checklistbank/issues/179
  Orchidaceae:
    - extinctoria # https://github.com/gbif/portal-feedback/issues/4170
  Cicadellidae:
    - guttulata # https://github.com/CatalogueOfLife/testing/issues/135
  Nymphalidae:
    - mylitta # https://github.com/gbif/portal-feedback/issues/4332


# List of uninomials (genus & above) known to be unique across all life for a given rank
# Only the first appearance of the name will create a taxon
# all subsequent ones will be merged into the first
enforceUnique:
  GENUS:
    - Anas


# specific list of CLB dataset keys to exclude as sectors being created for aboves source publisher keys
sourceDatasetExclusion:
- 292056 # genus chromista https://github.com/plazi/community/issues/349
- 4130 # Creates matching error https://github.com/CatalogueOfLife/data/issues/792
- 6675 # excluded to avoid duplicates
- 30084 # excluded due to wrong higher classification in all names  https://github.com/CatalogueOfLife/xcol/issues/179
- 28224 # temporaly blocked, https://github.com/plazi/community/issues/337
- 298906 # BDJ messy classification, https://github.com/CatalogueOfLife/data/issues/894
- 53474 # temporal block plazi dataset https://github.com/plazi/community/issues/388

# exclusion due to classification mismatch can be included when plazi fixes the issues
